# Generated by Django 6.0 on 2025-12-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wbs", "0002_wbsitem_level_wbsitem_lft_wbsitem_rght_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wbsitem",
            name="actual_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wbsitem",
            name="actual_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wbsitem",
            name="percent_complete",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="wbsitem",
            name="planned_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wbsitem",
            name="planned_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wbsitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not started"),
                    ("in_progress", "In progress"),
                    ("done", "Done"),
                    ("blocked", "Blocked"),
                ],
                default="not_started",
                max_length=20,
            ),
        ),
    ]
