# Generated by Django 6.0 on 2025-12-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbs', '0004_taskdependency'),
    ]

    operations = [
        migrations.AddField(
            model_name='wbsitem',
            name='sort_key',
            field=models.CharField(default='', editable=False, max_length=255),
        ),
    ]
