# Generated by Django 6.0 on 2025-12-05 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbs', '0007_projectissue_projecttask_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttask',
            name='wbs_item',
        ),
        migrations.CreateModel(
            name='ProjectItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('issue', 'Issue'), ('task', 'Task'), ('enhancement', 'Enhancement'), ('risk', 'Risk'), ('decision', 'Decision'), ('note', 'Note')], default='task', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('open', 'Open'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('done', 'Done'), ('closed', 'Closed')], default='todo', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('severity', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], help_text='Primarily for issues/bugs; may be left empty for simple tasks.', max_length=20, null=True)),
                ('reported_by', models.CharField(blank=True, max_length=100)),
                ('owner', models.CharField(blank=True, max_length=100)),
                ('date_started', models.DateTimeField(blank=True, null=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('estimate_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('external_ref', models.CharField(blank=True, help_text='Optional external ID (e.g. JIRA-123, GitHub #42).', max_length=100)),
                ('tags', models.CharField(blank=True, help_text="Comma-separated tags (e.g. 'scheduling,backend').", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wbs_item', models.ForeignKey(blank=True, help_text='Optional: link this item to a specific WBS item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_items', to='wbs.wbsitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ProjectIssue',
        ),
        migrations.DeleteModel(
            name='ProjectTask',
        ),
    ]
