# Generated by Django 6.0 on 2025-12-06 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wbs", "0011_tag_remove_projectitem_tags_projectitem_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wbsitem",
            name="code",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name="projectitem",
            index=models.Index(
                fields=["status", "-created_at"], name="projectitem_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectitem",
            index=models.Index(fields=["type", "-created_at"], name="projectitem_type_created_idx"),
        ),
        migrations.AddIndex(
            model_name="projectitem",
            index=models.Index(fields=["priority"], name="projectitem_priority_idx"),
        ),
        migrations.AddIndex(
            model_name="projectitem",
            index=models.Index(fields=["severity"], name="projectitem_severity_idx"),
        ),
        migrations.AddIndex(
            model_name="projectitem",
            index=models.Index(fields=["wbs_item", "status"], name="projectitem_wbs_status_idx"),
        ),
    ]
