# Generated by Django 6.0 on 2025-12-06

from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def forwards_func(apps, schema_editor):
    ProjectItem = apps.get_model("wbs", "ProjectItem")
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(app_label, model_name)

    owner_values = (
        ProjectItem.objects.exclude(owner__isnull=True)
        .exclude(owner="")
        .values_list("owner", flat=True)
        .distinct()
    )

    username_map = {}

    def get_or_create_user(raw_name: str):
        base = slugify(raw_name) or "user"
        candidate = base
        counter = 1
        while User.objects.filter(username=candidate).exists():
            candidate = f"{base}{counter}"
            counter += 1
        first_name = ""
        last_name = ""
        parts = raw_name.strip().split()
        if parts:
            first_name = parts[0]
            if len(parts) > 1:
                last_name = " ".join(parts[1:])
        user = User.objects.create(
            username=candidate,
            first_name=first_name,
            last_name=last_name,
        )
        return user

    for owner in owner_values:
        if owner in username_map:
            user = username_map[owner]
        else:
            user = User.objects.filter(username=slugify(owner)).first()
            if not user:
                user = get_or_create_user(owner)
            username_map[owner] = user
        ProjectItem.objects.filter(owner=owner).update(owner_user=user)


def backwards_func(apps, schema_editor):
    ProjectItem = apps.get_model("wbs", "ProjectItem")
    ProjectItem.objects.filter(owner_user__isnull=False).update(
        owner=models.F("owner_user__username")
    )


class Migration(migrations.Migration):

    dependencies = [
        ("wbs", "0012_alter_wbsitem_code_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="projectitem",
            name="owner_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name="project_items_temp",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(forwards_func, backwards_func),
        migrations.RemoveField(
            model_name="projectitem",
            name="owner",
        ),
        migrations.RenameField(
            model_name="projectitem",
            old_name="owner_user",
            new_name="owner",
        ),
        migrations.AlterField(
            model_name="projectitem",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name="project_items",
                help_text="Assigned owner (User).",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
