# Generated by Django 6.0 on 2025-12-08 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wbs", "0014_add_database_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="projectitem",
            name="wbs_projectitem_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="projectitem",
            name="wbs_projectitem_type_idx",
        ),
        migrations.RemoveIndex(
            model_name="projectitem",
            name="wbs_projectitem_priority_idx",
        ),
        migrations.RemoveIndex(
            model_name="projectitem",
            name="wbs_projectitem_wbs_item_idx",
        ),
        migrations.RemoveIndex(
            model_name="projectitem",
            name="wbs_projectitem_status_type_idx",
        ),
        migrations.RemoveIndex(
            model_name="projectitem",
            name="wbs_projectitem_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="tag",
            name="wbs_tag_name_idx",
        ),
        migrations.RemoveIndex(
            model_name="taskdependency",
            name="wbs_taskdep_predecessor_idx",
        ),
        migrations.RemoveIndex(
            model_name="taskdependency",
            name="wbs_taskdep_successor_idx",
        ),
        migrations.RemoveIndex(
            model_name="taskdependency",
            name="wbs_taskdep_pred_succ_idx",
        ),
        migrations.RemoveIndex(
            model_name="wbsitem",
            name="wbs_wbsitem_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="wbsitem",
            name="wbs_wbsitem_code_idx",
        ),
    ]
