# FreeCAD macro: build a joist assembly from the lumber_catalog.csv entries.
# Usage: Set the params below, then run the macro. It will create rim joists and interior joists
# spaced 16" OC (default) with a 3/4" offset for sheathing alignment. It pulls actual dimensions
# from the catalog row whose label matches `stock_label`.

import os
import sys
import FreeCAD as App
import Part

# Ensure this macro folder is on sys.path before importing helpers
_here = os.path.dirname(__file__)
if _here not in sys.path:
    sys.path.append(_here)

from lumber_common import ensure_macro_path, resolve_catalog, load_catalog, find_stock, attach_metadata, clear_group, make_hanger, inch

# Ensure helpers are importable if FreeCAD doesn't add macro dir to sys.path
ensure_macro_path()

# -----------------------
# Parameters (inches)
# -----------------------
# Resolve catalog path robustly: first next to this macro, then parent project FreeCAD/lumber.
_macro_dir = os.path.dirname(__file__)
_project_root = os.path.dirname(os.path.dirname(_macro_dir))
catalog_candidates = [
    os.path.join(_macro_dir, "lumber_catalog.csv"),
    os.path.join(_project_root, "FreeCAD", "lumber", "lumber_catalog.csv"),
]
catalog_path = resolve_catalog(catalog_candidates)

stock_label = "2x12x192"     # Which catalog entry to use (e.g., 2x12x192)
module_length = 195.0        # Overall X dimension (outer edge to outer edge) = full 16' joists + 2 rims (1.5" each)
module_width  = 192.0        # Overall Y dimension
spacing_oc    = 16.0         # On-center spacing for interior joists (inches)
offset_first_center = 0.00   # Joist_1 starts flush to rim (center at 0.75), see spacing logic below
make_pressure_treated = False  # If True, append "_PT" to label when looking up catalog
hanger_label = "hanger_LU210"
hanger_thickness = 0.06     # approx 16ga
hanger_height = 12.0        # fits 2x12 depth (11.25") with tolerance
hanger_seat_depth = 2.0     # back plate depth

# -----------------------
# Helpers
# -----------------------
# Board orientation: X = length, Y = thickness, Z = depth (so boards stand upright)
def make_box(length, thickness, depth):
    return Part.makeBox(inch(length), inch(thickness), inch(depth))

# -----------------------
# Main
# -----------------------
rows = load_catalog(catalog_path)
label_to_use = stock_label + "_PT" if make_pressure_treated else stock_label
row = find_stock(rows, label_to_use)
if not row:
    raise ValueError(f"Label '{label_to_use}' not found in catalog at {catalog_path}")

thick = float(row["actual_thickness_in"])
width = float(row["actual_width_in"])
stock_length = float(row["length_in"])  # 192", use full length (no cuts)

doc = App.ActiveDocument or App.newDocument("FloorJoists_from_catalog")

def make_joist(name, y_pos, length=module_length, depth=width, thick=thick):
    # X = length, Y = thickness, Z = depth (standing upright)
    box = make_box(length, thick, depth)
    shape = doc.addObject("Part::Feature", name)
    shape.Shape = box
    # Place so joists run along X; distribute along Y (spacing_oc)
    shape.Placement.Base = App.Vector(inch(thick), inch(y_pos - thick/2.0), 0)
    # Attach metadata
    attach_metadata(shape, row, label_to_use, supplier="lowes")
    return shape

def make_hanger(name, x_pos, y_center):
    # Simple U-shape via fused boxes
    bw = thick + 2 * hanger_thickness  # overall width across joist + flanges
    bh = hanger_height
    bd = hanger_seat_depth
    bt = hanger_thickness
    back = Part.makeBox(inch(bd), inch(bw), inch(bh))
    back.Placement.Base = App.Vector(inch(x_pos - bd), inch(y_center - bw/2.0), 0)
    sideL = Part.makeBox(inch(bd), inch(bt), inch(bh))
    sideL.Placement.Base = App.Vector(inch(x_pos - bd), inch(y_center - bw/2.0), 0)
    sideR = Part.makeBox(inch(bd), inch(bt), inch(bh))
    sideR.Placement.Base = App.Vector(inch(x_pos - bd), inch(y_center + bw/2.0 - bt), 0)
    seat = Part.makeBox(inch(bd), inch(bw), inch(bt))
    seat.Placement.Base = App.Vector(inch(x_pos - bd), inch(y_center - bw/2.0), 0)
    u_shape = back.fuse([sideL, sideR, seat])
    return make_hanger(doc, name, x_pos, y_center, thick, hanger_thickness, hanger_height, hanger_seat_depth, hanger_label=hanger_label)

# Rim joists at ends, running perpendicular to joists (along Y)
def make_rim(name, x_pos, length=module_width, depth=width, thick=thick):
    box = Part.makeBox(inch(thick), inch(length), inch(depth))  # X = thickness, Y = length, Z = depth
    shape = doc.addObject("Part::Feature", name)
    shape.Shape = box
    shape.Placement.Base = App.Vector(inch(x_pos - thick/2.0), 0, 0)
    for key in ("sku_lowes", "url_lowes", "sku_hd", "url_hd"):
        if key not in shape.PropertiesList:
            shape.addProperty("App::PropertyString", key)
        shape.__setattr__(key, row.get(key, ""))
    shape.addProperty("App::PropertyString", "supplier").supplier = "lowes"
    shape.addProperty("App::PropertyString", "label").label = label_to_use
    return shape

# Place rim joists: left rim centered at 0.75, right rim centered at module_length - 0.75
created = []
left_rim  = make_rim("Rim_Left", thick / 2.0, module_width); created.append(left_rim)
right_rim = make_rim("Rim_Right", module_length - (thick / 2.0), module_width); created.append(right_rim)

# Interior joists
positions = []
# Spacing rules:
# - Joist_1: center at 0.75" (flush to left rim)
# - Joist_2: center at 15.25" (15-1/4" from Joist_1)
# - Joists 3..n: 16" OC progression
# - Final joist: forced to center at (module_width - 0.75) to align to right rim
first_center = thick / 2.0                     # 0.75"
second_center = first_center + 15.25           # 15.25" from first
positions = [first_center, second_center]

# Fill remaining joists at 16" OC until near far rim
next_center = second_center + spacing_oc
while next_center < module_width - (thick / 2.0):
    positions.append(next_center)
    next_center += spacing_oc

# Force final joist to align to far rim (center 0.75" from edge)
last_center = module_width - (thick / 2.0)
if positions[-1] != last_center:
    positions.append(last_center)

# Build joists with full-length stock
for idx, y_pos in enumerate(positions, start=1):
    created.append(make_joist(f"Joist_{idx}", y_pos, stock_length))

# Add hangers at both ends of each joist
left_face_x = thick / 2.0
right_face_x = module_length - (thick / 2.0)
for idx, y_pos in enumerate(positions, start=1):
    created.append(make_hanger(f"Hanger_L_{idx}", left_face_x, y_pos))
    created.append(make_hanger(f"Hanger_R_{idx}", right_face_x, y_pos))

group_name = "Joist_Module_2x12_16x16"
clear_group(doc, group_name)
group = doc.addObject("App::DocumentObjectGroup", group_name)
group.addObjects(created)
group.Group = created

doc.recompute()
