# FreeCAD macro: build a 16' x 8' joist assembly (2x12 stock) from lumber_catalog.csv.
# Orientation: X = 16' run (192"), Y = width (96"), boards stand upright (X=length, Y=thickness, Z=depth).
# Spacing: 16" OC, no initial 3/4" offset (starts at origin-aligned center).

import os
import sys
import FreeCAD as App
import Part

# Ensure this macro folder is on sys.path before importing helpers
_here = os.path.dirname(__file__)
if _here not in sys.path:
    sys.path.append(_here)

from lumber_common import ensure_macro_path, resolve_catalog, load_catalog, find_stock, attach_metadata, clear_group, make_hanger, inch
from lumber_common import make_hanger as make_hanger_helper

ensure_macro_path()

# -----------------------
# Parameters (inches)
# -----------------------
_macro_dir = os.path.dirname(__file__)
_project_root = os.path.dirname(os.path.dirname(_macro_dir))
catalog_candidates = [
    os.path.join(_macro_dir, "lumber_catalog.csv"),
    os.path.join(_project_root, "FreeCAD", "lumber", "lumber_catalog.csv"),
]
catalog_path = resolve_catalog(catalog_candidates)

stock_label = "2x12x192"     # Which catalog entry to use (e.g., 2x12x192)
module_length = 195.0        # Overall X dimension (outer edge to outer edge) = full 16' joists + 2 rims
module_width  = 96.0         # Overall Y dimension (8')
spacing_oc    = 16.0         # On-center spacing for interior joists (inches)
offset_first_center = 0.00   # Joist_1 starts flush to rim (center at 0.75), see spacing logic below
make_pressure_treated = False  # If True, append "_PT" to label when looking up catalog
hanger_label = "hanger_LU210"
hanger_thickness = 0.06     # approx 16ga
hanger_height = 7.8125      # ~7-13/16" overall height
hanger_seat_depth = 2.0     # back plate depth

# -----------------------
# Helpers
# -----------------------
def inch(x): return x * 25.4

# Board orientation: X = length, Y = thickness, Z = depth (so boards stand upright)
def make_box(length, thickness, depth):
    return Part.makeBox(inch(length), inch(thickness), inch(depth))

# -----------------------
# Main
# -----------------------
rows = load_catalog(catalog_path)
label_to_use = stock_label + "_PT" if make_pressure_treated else stock_label
row = find_stock(rows, label_to_use)
if not row:
    raise ValueError(f"Label '{label_to_use}' not found in catalog at {catalog_path}")

thick = float(row["actual_thickness_in"])
width = float(row["actual_width_in"])
stock_length = float(row["length_in"])  # 192", use full length (no cuts)

doc = App.ActiveDocument or App.newDocument("Joist_Module_2x12_16x8")

def make_joist(name, y_pos, length=module_length, depth=width, thick=thick):
    # X = length, Y = thickness, Z = depth (standing upright)
    box = make_box(length, thick, depth)
    shape = doc.addObject("Part::Feature", name)
    shape.Shape = box
    shape.Placement.Base = App.Vector(inch(thick), inch(y_pos - thick/2.0), 0)
    attach_metadata(shape, row, label_to_use, supplier="lowes")
    return shape

def make_hanger(name, x_pos, y_center):
    return make_hanger_helper(doc, name, x_pos, y_center, thick, hanger_thickness, hanger_height, hanger_seat_depth, hanger_label)

# Rim joists at ends, running perpendicular to joists (along Y)
def make_rim(name, x_pos, length=module_width, depth=width, thick=thick):
    box = Part.makeBox(inch(thick), inch(length), inch(depth))  # X = thickness, Y = length, Z = depth
    shape = doc.addObject("Part::Feature", name)
    shape.Shape = box
    shape.Placement.Base = App.Vector(inch(x_pos - thick/2.0), 0, 0)
    for key in ("sku_lowes", "url_lowes", "sku_hd", "url_hd"):
        if key not in shape.PropertiesList:
            shape.addProperty("App::PropertyString", key)
        shape.__setattr__(key, row.get(key, ""))
    shape.addProperty("App::PropertyString", "supplier").supplier = "lowes"
    shape.addProperty("App::PropertyString", "label").label = label_to_use
    return shape

created = []

# Rims: left centered at 0.75, right centered at module_length - 0.75 (matching 16x16 logic)
left_rim  = make_rim("Rim_Left", thick / 2.0, module_width); created.append(left_rim)
right_rim = make_rim("Rim_Right", module_length - (thick / 2.0), module_width); created.append(right_rim)

# Interior joists
positions = []
# Spacing rules:
# - Joist_1: center at 0.75" (flush to left rim)
# - Joist_2: center at 15.25" (15-1/4" from Joist_1)
# - Joists 3..n: 16" OC progression
# - Final joist: forced to center at (module_width - 0.75) to align to right rim
first_center = thick / 2.0                     # 0.75"
second_center = first_center + 15.25           # 15.25" from first
positions = [first_center, second_center]

# Fill remaining joists at 16" OC until near far rim
next_center = second_center + spacing_oc
while next_center < module_width - (thick / 2.0):
    positions.append(next_center)
    next_center += spacing_oc

# Force final joist to align to far rim (center 0.75" from edge)
last_center = module_width - (thick / 2.0)
if positions[-1] != last_center:
    positions.append(last_center)

# Build joists
for idx, y_pos in enumerate(positions, start=1):
    created.append(make_joist(f"Joist_{idx}", y_pos, stock_length))

# Add hangers on rims for interior joists only (skip first/last joist)
# Place back plate/seat with interior face at the rim interior (seat extends -X)
left_base_x = thick
right_base_x = module_length - thick
for idx, y_pos in enumerate(positions, start=1):
    if idx == 1 or idx == len(positions):
        continue
    created.append(make_hanger(f"Hanger_L_{idx}", left_base_x, y_pos))
    created.append(make_hanger(f"Hanger_R_{idx}", right_base_x, y_pos))

# Group the assembly so it behaves as a single module in the tree
group_name = "Joist_Module_2x12_16x8"
group = doc.addObject("App::DocumentObjectGroup", group_name)
group.Label = group_name
group.addObjects(created)
group.Group = created

doc.recompute()
